In [1]:
import numpy as np
import pandas as pd

In [47]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

# Creating a NumPy array 'arr' of integers from 0 to 5
arr = np.arange(6)

# Printing the array and its data type
print(arr)
print("Data type of arr :",arr.dtype)



[0 1 2 3 4 5]
Data type of arr : int64


In [48]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

# Given NumPy array 'arr'
arr = np.array([1.5, 2.6, 3.7])

# Checking if the data type is float64
is_float64 = arr.dtype == np.float64

# Printing the result
print("Is the data type float64 ? ", is_float64)


Is the data type float64 ?  True


In [49]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.


# Creating a NumPy array 'arr' with complex128 data type
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)

# Printing the array and its data type
print(arr)
print("Data Type:",arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
Data Type: complex128


In [50]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

# Creating a NumPy array 'arr' of integers
arr = np.array([1, 2, 3, 4, 5])

# Converting the array to float32
arr_float32 = arr.astype(np.float32)

# Printing the original and converted arrays along with their data types
print("Original Array:", arr)
print("Converted Array:", arr_float32)


Original Array: [1 2 3 4 5]
Converted Array: [1. 2. 3. 4. 5.]


In [51]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


# Creating a NumPy array 'arr' with float64 data type
arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)

# Displaying the original array and its data type
print("Original Array:", arr)
print("Original Data Type:", arr.dtype)

# Converting the array to float32
arr_float32 = arr.astype(np.float32)

# Displaying the converted array and its new data type
print("Converted Array:", arr_float32)
print("Converted Data Type:", arr_float32.dtype)


Original Array: [1.5 2.6 3.7]
Original Data Type: float64
Converted Array: [1.5 2.6 3.7]
Converted Data Type: float32


In [52]:
# 6.  Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
    shape = arr.shape        # Get the shape of the array
    size = arr.size          # Get the total number of elements in the array
    dtype = arr.dtype        # Get the data type of the array

    return shape, size, dtype

# Example usage
if __name__ == "__main__":
    # Creating a sample NumPy array
    sample_array = np.array([[1.5, 2.6], [3.7, 4.8]], dtype=np.float64)

    # Getting the attributes of the sample array
    attributes = array_attributes(sample_array)

    # Printing the attributes
    print("Sample array:")
    print(sample_array)
    print("Shape:", attributes[0])
    print("Size:", attributes[1])
    print("Data Type:", attributes[2])

Sample array:
[[1.5 2.6]
 [3.7 4.8]]
Shape: (2, 2)
Size: 4
Data Type: float64


In [53]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


 # Creating function array_dimension
def array_dimension(arr):
    return arr.ndim  # Return the number of dimensions

# Example usage
if __name__ == "__main__":
    # Creating a sample NumPy array
    sample_array_1d = np.array([1, 2, 3])            # 1D array
    sample_array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
    sample_array_3d = np.array([[[1], [2]], [[3], [4]]])  # 3D array

    # Getting the dimensions of the sample arrays
    print("Dimensionality of sample_array1:", array_dimension(sample_array_1d))
    print("Dimensionality of sample_array2:", array_dimension(sample_array_2d))
    print("Dimensionality of sample_array3:", array_dimension(sample_array_3d))

Dimensionality of sample_array1: 1
Dimensionality of sample_array2: 2
Dimensionality of sample_array3: 3


In [54]:
# 8.  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

  # Creating function item_size
def item_size_info(arr):
    item_size = arr.itemsize  # Size of one element in bytes
    total_size = arr.nbytes    # Total size of the array in bytes

    return item_size, total_size

# Example usage
if __name__ == "__main__":
    # Creating a sample NumPy array
    sample_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

    # Getting the item size and total size of the sample array
    sizes = item_size_info(sample_array)

    # Printing the results
    print("Sample Array:")
    print(sample_array)
    print("Item Size (in bytes):", sizes[0])
    print("Total Size (in bytes):", sizes[1])

Sample Array:
[[1. 2. 3.]
 [4. 5. 6.]]
Item Size (in bytes): 8
Total Size (in bytes): 48


In [55]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

  # Creating function array_strides
def array_strides(arr):
    return arr.strides  # Return the strides of the array

# Example usage
if __name__ == "__main__":
    # Creating a sample NumPy array
    sample_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

    # Getting the strides of the sample array
    strides = array_strides(sample_array)

    # Printing the results
    print("Sample Array:")
    print(sample_array)
    print("Strides of Array (in bytes):", strides)

Sample Array:
[[1. 2. 3.]
 [4. 5. 6.]]
Strides of Array (in bytes): (24, 8)


In [56]:
# 10.  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

  # Creating function shape_stride_realationship
def shape_stride_relationship(arr):
    shape = arr.shape      # Get the shape of the array
    strides = arr.strides  # Get the strides of the array

    return shape, strides  # Return both shape and strides

# Example usage
if __name__ == "__main__":
    # Creating a sample NumPy array
    sample_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

    # Getting the shape and strides of the sample array
    result = shape_stride_relationship(sample_array)

    # Printing the results
    print("Sample Array:")
    print(sample_array)
    print("Shape:", result[0])
    print("Strides (in bytes):", result[1])

Sample Array:
[[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3)
Strides (in bytes): (24, 8)


In [57]:
# 11.  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

   # Creating function create_zeros_array
def create_zeros_array(n):
    return np.zeros(n)  # Create and return an array of zeros with n elements

# Example usage
if __name__ == "__main__":
    # Specify the number of elements
    n = 5

    # Creating the zeros array
    zeros_array = create_zeros_array(n)

    # Printing the result
    print("Input Integer:",n)
    print("Array of zeros:", zeros_array)

Input Integer: 5
Array of zeros: [0. 0. 0. 0. 0.]


In [58]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

 # Create function create_ones_matrix
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))  # Create and return a 2D array of ones

# Example usage
if __name__ == "__main__":
    # Specify the number of rows and columns
    rows = 3
    cols = 4

    # Creating the ones matrix
    ones_matrix = create_ones_matrix(rows, cols)

    # Printing the result
    print("Number of rows:", rows)
    print("Number of columns:", cols)
    print("Matrix of ones:\n", ones_matrix)

Number of rows: 3
Number of columns: 4
Matrix of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [59]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified`step.

  # Create function generate_range_array
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)  # Create and return the range array

# Example usage
if __name__ == "__main__":
    # Specify the start, stop, and step values
    start = 0
    stop = 13
    step = 2

    # Generating the range array
    range_array = generate_range_array(start, stop, step)

    # Printing the result
    print("Start Value:", start)
    print("Stop Value (exclusive):", stop)
    print("Step Value:", step)
    print("Generated Range Array:", range_array)

Start Value: 0
Stop Value (exclusive): 13
Step Value: 2
Generated Range Array: [ 0  2  4  6  8 10 12]


In [60]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

 # Create function generate_linear_space
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)  # Create and return the linear space array

# Example usage
if __name__ == "__main__":
    # Specify the start, stop, and number of values
    start = 0.0
    stop = 1.0
    num = 5

    # Generating the linear space array
    linear_space_array = generate_linear_space(start, stop, num)

    # Printing the result
    print("Start Value:", start)
    print("Stop Value (inclusive):", stop)
    print("Number of Values:", num)
    print("Generated Linear Space Array:", linear_space_array)

Start Value: 0.0
Stop Value (inclusive): 1.0
Number of Values: 5
Generated Linear Space Array: [0.   0.25 0.5  0.75 1.  ]


In [61]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

 # Create function create_identity_matrix
def create_identity_matrix(n):
    return np.eye(n)  # Create and return the identity matrix

# Example usage
if __name__ == "__main__":
    # Specify the size of the identity matrix
    n = 4

    # Creating the identity matrix
    identity_matrix = create_identity_matrix(n)

    # Printing the result
    print("Size of Identity Matrix:", n)
    print("Identity Matrix of size", n, "x", n, ":\n", identity_matrix)

Size of Identity Matrix: 4
Identity Matrix of size 4 x 4 :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [62]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

 # Create funtion that convert python list into Numpy array
def convert_list_to_array(py_list):
    return np.array(py_list)  # Convert the list to a NumPy array

# Example usage
if __name__ == "__main__":
    # Specify a Python list
    python_list = [1, 2, 3, 4, 5]

    # Converting the list to a NumPy array
    numpy_array = convert_list_to_array(python_list)

    # Printing the result
    print("Original Python List:", python_list)
    print("Converted NumPy Array:", numpy_array)

Original Python List: [1, 2, 3, 4, 5]
Converted NumPy Array: [1 2 3 4 5]


In [63]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

 # Create function to demonstrate use of `numpy.view`
def demonstrate_view():
    # Creating a NumPy array
    original_array = np.array([1, 2, 3, 4, 5])

    # Creating a view of the original array
    array_view = original_array.view()

    # Displaying both arrays
    print("Original Array:", original_array)
    print("Array View:", array_view)

    # Modifying the view
    array_view[0] = 10

    # Displaying both arrays after modification
    print("\nAfter modifying the view:")
    print("Original Array:", original_array)
    print("Array View:", array_view)

# Example usage
if __name__ == "__main__":
    demonstrate_view()

Original Array: [1 2 3 4 5]
Array View: [1 2 3 4 5]

After modifying the view:
Original Array: [10  2  3  4  5]
Array View: [10  2  3  4  5]


In [64]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)  # Concatenate the arrays

# Example usage
if __name__ == "__main__":
    # Creating two sample NumPy arrays
    array1 = np.array([[1, 2], [3, 4]])
    array2 = np.array([[5, 6], [7, 8]])

    # Concatenating the arrays along the default axis (0)
    concatenated_array_axis0 = concatenate_arrays(array1, array2)

    # Concatenating the arrays along axis 1
    concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)

    # Printing the results
    print("Array 1:\n", array1)
    print("Array 2:\n", array2)
    print("\nConcatenated Array along axis 0:\n", concatenated_array_axis0)
    print("\nConcatenated Array along axis 1:\n", concatenated_array_axis1)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Concatenated Array along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated Array along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [65]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.


def concatenate_arrays_horizontally(array1, array2):
    # Check if the number of rows is the same
    if array1.shape[0] != array2.shape[0]:
        raise ValueError("The number of rows in both arrays must be the same for horizontal concatenation.")

    # Concatenate the arrays along axis 1 (horizontally)
    return np.concatenate((array1, array2), axis=1)

# Example usage
if __name__ == "__main__":
    # Creating two sample NumPy arrays with the same number of rows
    array1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
    array2 = np.array([[7, 8], [9, 10]])        # Shape (2, 2)

    # Concatenating the arrays horizontally
    concatenated_array = concatenate_arrays_horizontally(array1, array2)

    # Printing the result
    print("Array 1:\n", array1)
    print("Array 2:\n", array2)
    print("\nConcatenated Array:\n", concatenated_array)




Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8]
 [ 9 10]]

Concatenated Array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [66]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.


def stack_arrays_vertically(arrays):
    return np.vstack(arrays)  # Use vstack to concatenate the arrays vertically

# Example usage
if __name__ == "__main__":
    # Creating sample NumPy arrays
    array1 = np.array([[1, 2, 3], [4, 5, 6]])
    array2 = np.array([[7, 8, 9]])
    array3 = np.array([[10, 11, 12], [13, 14, 15]])

    # List of arrays to stack
    arrays_to_stack = [array1, array2, array3]

    # Stacking the arrays vertically
    stacked_array = stack_arrays_vertically(arrays_to_stack)

    # Printing the result
    print("Array1:\n",array1)
    print("Array2:\n",array2)
    print("Array3:\n",array3)
    print("\nStacked Array:\n", stacked_array)


Array1:
 [[1 2 3]
 [4 5 6]]
Array2:
 [[7 8 9]]
Array3:
 [[10 11 12]
 [13 14 15]]

Stacked Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [67]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.


def create_integer_range(start, stop, step):
    # Generate the range and include the stop value if it's not already included
    if step > 0:
        return np.arange(start, stop + 1, step)  # Include stop by adding 1
    else:
        return np.arange(start, stop - 1, step)  # For negative steps, adjust accordingly

# Example usage
if __name__ == "__main__":
    # Specify the range and step size
    start = 1
    stop = 10
    step = 3

    # Creating the integer range array
    integer_range_array = create_integer_range(start, stop, step)

    # Printing the result
    print("Generated Integer Range Array:", integer_range_array)



Generated Integer Range Array: [ 1  4  7 10]


In [68]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


def generate_equally_spaced_values(start=0, stop=1, num=10):
    return np.linspace(start, stop, num)  # Generate equally spaced values

# Example usage
if __name__ == "__main__":
    # Generating the array of equally spaced values
    equally_spaced_array = generate_equally_spaced_values()

    # Printing the result
    print("Start Value:", start)
    print("Stop Value:", stop)
    print("\n10 Equally Spaced Values Array:\n", equally_spaced_array)



Start Value: 1
Stop Value: 10

10 Equally Spaced Values Array:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [69]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


def generate_logarithmically_spaced_values(start=1, stop=1000, num=5):
    return np.logspace(np.log10(start), np.log10(stop), num)  # Generate log spaced values

# Example usage
if __name__ == "__main__":
    # Generating the array of logarithmically spaced values
    log_spaced_array = generate_logarithmically_spaced_values()

    # Printing the result
    print("Start Value:", start)
    print("Stop Value:", stop)
    print("\n5 Logarithmically Spaced Values Array:\n", log_spaced_array)



Start Value: 1
Stop Value: 10

5 Logarithmically Spaced Values Array:
 [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [70]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.


def create_dataframe_from_random_integers(rows=5, cols=3, low=1, high=100):
    # Generate a NumPy array of random integers
    random_array = np.random.randint(low, high, size=(rows, cols))

    # Create a DataFrame from the NumPy array
    df = pd.DataFrame(random_array, columns=[f'Column {i+1}' for i in range(cols)])

    return df

# Example usage
if __name__ == "__main__":
    # Creating the DataFrame
    dataframe = create_dataframe_from_random_integers()

    # Printing the result
    print("Generated DataFrame:\n", dataframe)



Generated DataFrame:
    Column 1  Column 2  Column 3
0        75        37        19
1        43         1        15
2        87        29        80
3        96         7        47
4        83        29        67


In [71]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.


def replace_negative_with_zero(df, column_name):
    # Replace negative values with zero using NumPy where
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])

    return df

# Example usage
if __name__ == "__main__":
    # Creating a sample DataFrame
    data = {
        'A': [1, -2, 3, -4, 5],
        'B': [-1, 2, -3, 4, -5],
        'C': [10, -20, 30, -40, 50]
    }

    df = pd.DataFrame(data)
    print("Original DataFrame:\n", df)

    # Replacing negative values in column 'A'
    modified_df = replace_negative_with_zero(df, 'A')

    print("\nModified DataFrame (negative values in column 'A' replaced with zeros):\n", modified_df)



Original DataFrame:
    A  B   C
0  1 -1  10
1 -2  2 -20
2  3 -3  30
3 -4  4 -40
4  5 -5  50

Modified DataFrame (negative values in column 'A' replaced with zeros):
    A  B   C
0  1 -1  10
1  0  2 -20
2  3 -3  30
3  0  4 -40
4  5 -5  50


In [72]:
# 26. Access the 3rd element from the given NumPy array ,arr = np.array([10, 20, 30, 40, 50]).

# Create the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

# Print the result
print("Original Array:", arr)
print("The 3rd element is:", third_element)



Original Array: [10 20 30 40 50]
The 3rd element is: 30


In [73]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array  arr_2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

# Create the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Access the element at index (1, 2)
element = arr_2d[1, 2]

# Print the result
print("Original 2D Array:",arr_2d)
print("The element at index (1, 2) is:", element)




Original 2D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
The element at index (1, 2) is: 6


In [74]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array , arr = np.array([3, 8, 2, 10, 5, 7]).

# Create the NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Use boolean indexing to extract elements greater than 5
greater_than_five = arr[arr > 5]

# Print the result
print("Original Array:", arr)

print("Elements greater than 5:", greater_than_five)



Original Array: [ 3  8  2 10  5  7]
Elements greater than 5: [ 8 10  7]


In [75]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array, arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).

# Create the NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform slicing to extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]  # This will include indices 2, 3, 4, and 5

# Print the result
print("Original Array:", arr)
print("Extracted elements from index 2 to 5 (inclusive):", sliced_array)


Original Array: [1 2 3 4 5 6 7 8 9]
Extracted elements from index 2 to 5 (inclusive): [3 4 5 6]


In [76]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array , arr_2d = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]]).


# Create the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

# Print the result
print("Original 2D Array:\n", arr_2d)
print("\nExtracted Sub-array:\n", sub_array)




Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Extracted Sub-array:
 [[2 3]
 [5 6]]


In [77]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.


def extract_elements(arr_2d, row_indices, col_indices):
    # Use advanced indexing to extract specified elements
    return arr_2d[row_indices[:, None], col_indices]

# Example usage
if __name__ == "__main__":
    # Define a 2D NumPy array
    arr_2d = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

    # Define arrays of row and column indices to extract
    row_indices = np.array([0, 1])  # From first row (index 0) and second row (index 1)
    col_indices = np.array([1, 2])  # From first row: index 1 and second row: index 2

    # Extract the elements based on the specified indices
    extracted_elements = extract_elements(arr_2d, row_indices, col_indices)

    # Print the result
    print("Extracted Elements:\n", extracted_elements)





Extracted Elements:
 [[2 3]
 [5 6]]


In [78]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.



def filter_elements_greater_than_threshold(arr, threshold):
    # Use boolean indexing to filter elements greater than the threshold
    filtered_array = arr[arr > threshold]

    return filtered_array

# Example usage
if __name__ == "__main__":
    # Define a 1D NumPy array
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

    # Define the threshold
    threshold = 5

    # Filter the elements greater than the threshold
    result = filter_elements_greater_than_threshold(arr, threshold)

    # Print the result
    print("Original Array:", arr)
    print("Elements greater than", threshold, ":", result)



Original Array: [1 2 3 4 5 6 7 8 9]
Elements greater than 5 : [6 7 8 9]


In [79]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.


def extract_elements(arr, x_indices, y_indices, z_indices):
    # Use advanced indexing to extract the elements
    return arr[x_indices, y_indices, z_indices]

# Example usage
# Creating a smaller 3D array with shape (3, 3, 3) and integer values
arr = np.random.randint(0, 100, size=(3, 3, 3))  # Random integers between 0 and 100

# Display the array for reference
print("Original 3D array (3x3x3) with integer values:")
print(arr)

# Indices for each dimension
x_indices = np.array([0, 1])  # x indices (along the first dimension)
y_indices = np.array([1, 2])  # y indices (along the second dimension)
z_indices = np.array([2, 0])  # z indices (along the third dimension)

# Extracting elements using the function
extracted_elements = extract_elements(arr, x_indices, y_indices, z_indices)

# Displaying the extracted elements
print("\nExtracted elements from the array:")
print(extracted_elements)





Original 3D array (3x3x3) with integer values:
[[[15 31 78]
  [73 85 79]
  [ 7  6 55]]

 [[74 99 92]
  [81  1  1]
  [60 54 12]]

 [[33 51 34]
  [47 61 96]
  [86  6 73]]]

Extracted elements from the array:
[79 60]


In [80]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


def filter_elements_with_conditions(arr, condition1, condition2):
    # Create boolean masks based on the conditions
    mask1 = condition1(arr)
    mask2 = condition2(arr)

    # Combine both masks using the logical AND operator
    combined_mask = mask1 & mask2

    # Use boolean indexing to select elements that meet both conditions
    return arr[combined_mask]

# Example usage
if __name__ == "__main__":
    # Create a sample 1D NumPy array
    array_1d = np.array([1, 5, 10, 15, 20, 25, 30, 35, 40])

    # Define conditions: elements greater than 10 and less than 30
    condition1 = lambda x: x > 10
    condition2 = lambda x: x < 30

    # Filter the elements based on the specified conditions
    filtered_elements = filter_elements_with_conditions(array_1d, condition1, condition2)

    # Print the result
    print("Original Array:", array_1d)
    print("Filtered Elements:", filtered_elements)



Original Array: [ 1  5 10 15 20 25 30 35 40]
Filtered Elements: [15 20 25]


In [81]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


def extract_elements(arr_2d, row_indices, col_indices):
    # Use advanced indexing to extract specified elements
    return arr_2d[row_indices, col_indices]

# Example usage
if __name__ == "__main__":
    # Define a 2D NumPy array
    arr_2d = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

    # Define arrays of indices for rows and columns
    row_indices = np.array([0, 1])  # Select from the first row (index 0) and second row (index 1)
    col_indices = np.array([1, 2])  # Select columns at index 1 and index 2

    # Extract the elements based on the specified indices
    extracted_elements = extract_elements(arr_2d, row_indices, col_indices)

    # Print the result
    print("Extracted Elements:\n", extracted_elements)



Extracted Elements:
 [2 6]


In [82]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


def add_scalar_to_array(arr, scalar):
    return arr + scalar

# Example usage
if __name__ == "__main__":
    # Create a 2D NumPy array of shape (3, 3)
    array_2d = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

    # Define the scalar value
    scalar_value = 5

    # Add the scalar to the array using the function
    result_array = add_scalar_to_array(array_2d, scalar_value)

    # Print the original and resulting arrays
    print("Original Array:\n", array_2d)
    print("Resulting Array after adding", scalar_value, ":\n", result_array)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Resulting Array after adding 5 :
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [83]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.


def multiply_with_broadcasting(arr1, arr2):
    # Ensure arr1 has shape (3,) for proper broadcasting
    return arr1.flatten()[:, np.newaxis] * arr2

# Example usage
if __name__ == "__main__":
    # Define a 1D array of shape (3,)
    arr1 = np.array([2, 3, 4])  # Shape (3,) - no need for extra dimension

    # Define a 2D array of shape (3, 4)
    arr2 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])  # Shape (3, 4)

    # Perform multiplication using the function
    result = multiply_with_broadcasting(arr1, arr2)

    # Print the result
    print("Array 1:\n", arr1)
    print("Array 2:\n", arr2)
    print("\nResulting Array:\n", result)



Array 1:
 [2 3 4]
Array 2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Resulting Array:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [84]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

def add_vector_to_matrix(arr1, arr2):
    # Ensure arr1 is reshaped to be compatible for broadcasting with arr2
    return arr2 + arr1.flatten()[:, np.newaxis]

# Example usage
if __name__ == "__main__":
    # Define a 1D array of shape (4,)
    arr1 = np.array([2, 3, 4, 5])   # Shape (4,) - no need for extra dimension

    # Define a 2D array of shape (4,3)
    arr2 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10,11,12]])   # Shape (4,3)

    # Perform addition using the function
    result = add_vector_to_matrix(arr1.reshape(4, -1), arr2)

    # Print the result
    print("Resulting Array:\n", result)





Resulting Array:
 [[ 3  4  5]
 [ 7  8  9]
 [11 12 13]
 [15 16 17]]


In [85]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.


def add_arrays_with_broadcasting(arr1, arr2):
    return arr1 + arr2

# Example usage
if __name__ == "__main__":
    # Define a 2D array of shape (3, 1)
    arr1 = np.array([[1],
                     [2],
                     [3]])  # Shape (3, 1)

    # Define a 2D array of shape (1, 3)
    arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)

    # Perform addition using the function
    result = add_arrays_with_broadcasting(arr1, arr2)

    # Print the result
    print("Array 1:\n", arr1)
    print("Array 2:\n", arr2)
    print("\nResulting Array:\n", result)




Array 1:
 [[1]
 [2]
 [3]]
Array 2:
 [[4 5 6]]

Resulting Array:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [86]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.


def multiply_with_broadcasting(arr1, arr2):
    # Reshape arr2 to (2, 1, 2) for broadcasting with arr1
    arr2_reshaped = arr2[:, :, np.newaxis]  # Shape becomes (2, 2, 1)

    # Now arr1 has shape (2, 3) and arr2_reshaped has shape (2, 2, 1)
    arr1_repeated = np.repeat(arr1[:, np.newaxis, :], arr2.shape[1], axis=1)  # Shape becomes (2, 2, 3)

    # Perform multiplication
    result = arr1_repeated * arr2_reshaped

    return result

# Example usage
if __name__ == "__main__":
    # Define a 2D array of shape (2, 3)
    arr1 = np.array([[1, 2, 3],
                     [4, 5, 6]])   # Shape (2, 3)

    # Define a 2D array of shape (2, 2)
    arr2 = np.array([[7, 8],
                     [9, 10]])     # Shape (2, 2)

    # Perform multiplication using the function
    result = multiply_with_broadcasting(arr1, arr2)

    # Print the result
    print("Array 1:\n", arr1)
    print("Array 2:\n", arr2)
    print("\nResulting Array:\n", result)



Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8]
 [ 9 10]]

Resulting Array:
 [[[ 7 14 21]
  [ 8 16 24]]

 [[36 45 54]
  [40 50 60]]]


In [87]:
# 41. Calculate column wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]]) ,

# Given array
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Calculate column-wise mean
column_means = arr.mean(axis=0)

# Print the result
print("Original Array:\n", arr)
print("Column-wise mean:", column_means)



Original Array:
 [[1 2 3]
 [4 5 6]]
Column-wise mean: [2.5 3.5 4.5]


In [88]:
# 42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]]).

# Given array
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Calculate maximum value in each row
row_maximums = np.max(arr, axis=1)

# Print the result
print("Original Array:\n", arr)
print("Maximum value in each row:", row_maximums)


Original Array:
 [[1 2 3]
 [4 5 6]]
Maximum value in each row: [3 6]


In [89]:
# 43. For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]]) .

# Given array
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Find indices of maximum value in each column
max_indices = np.argmax(arr, axis=0)

# Print the result
print("Original Array:\n", arr)
print("Indices of maximum values in each column:", max_indices)


Original Array:
 [[1 2 3]
 [4 5 6]]
Indices of maximum values in each column: [1 1 1]


In [90]:
# 44. For the given array, apply custom function to calculate moving sum along rows:arr = np.array([[1, 2, 3], [4, 5, 6]]) .


def moving_sum(arr):
    return np.convolve(arr, np.ones(2), 'valid')

def apply_moving_sum(arr):
    return np.apply_along_axis(moving_sum, axis=1, arr=arr)

# Given array
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Calculate moving sum along rows
result = apply_moving_sum(arr)

# Print the result
print("Original Array:\n", arr)
print("\nMoving sum along rows:\n", result)


Original Array:
 [[1 2 3]
 [4 5 6]]

Moving sum along rows:
 [[ 3.  5.]
 [ 9. 11.]]


In [91]:
# 45. In the given array, check if all elements in each column are even : arr = np.array([[2, 4, 6], [3, 5, 7]]).


# Given array
arr = np.array([[2, 4, 6],
                 [3, 5, 7]])

# Check if all elements in each column are even
are_all_even = np.all(arr % 2 == 0, axis=0)

# Print the result
print("Original Array:\n", arr)
print("Are all elements in each column even?", are_all_even)


Original Array:
 [[2 4 6]
 [3 5 7]]
Are all elements in each column even? [False False False]


In [92]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6])


# Given original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Specify the desired shape (m rows and n columns)
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

# Print the reshaped matrix
print("Original Array:\n", original_array)
print("\nReshaped Matrix:\n", reshaped_matrix)



Original Array:
 [1 2 3 4 5 6]

Reshaped Matrix:
 [[1 2 3]
 [4 5 6]]


In [93]:
# 47. Create a function that takes a matrix as input and returns the flattened array. input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


def flatten_matrix(input_matrix):
    return input_matrix.flatten()  # or use input_matrix.ravel()

# Example usage
if __name__ == "__main__":
    # Given input matrix
    input_matrix = np.array([[1, 2, 3],
                              [4, 5, 6]])

    # Flatten the matrix
    flattened_array = flatten_matrix(input_matrix)

    # Print the result
    print("Original Matrix:\n", input_matrix)
    print("Flattened Array:", flattened_array)


Original Matrix:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]


In [94]:
# 48. Write a function that concatenates two given arrays along a specified axis. array1 = np.array([[1, 2], [3, 4]]) array2 = np.array([[5, 6], [7, 8]]).


def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

# Example usage
if __name__ == "__main__":
    # Given arrays
    array1 = np.array([[1, 2],
                       [3, 4]])

    array2 = np.array([[5, 6],
                       [7, 8]])

    # Concatenate the arrays along axis 0 (rows)
    result_axis_0 = concatenate_arrays(array1, array2, axis=0)

    # Concatenate the arrays along axis 1 (columns)
    result_axis_1 = concatenate_arrays(array1, array2, axis=1)

    # Print the results
    print("Concatenated along axis 0:\n", result_axis_0)
    print("Concatenated along axis 1:\n", result_axis_1)



Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [95]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis. original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).


def split_array(original_array, num_splits, axis=0):
    return np.array_split(original_array, num_splits, axis=axis)

# Example usage
if __name__ == "__main__":
    # Given original array
    original_array = np.array([[1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 9]])

    # Split the array into 3 parts along axis 0 (rows)
    split_result_axis_0 = split_array(original_array, num_splits=3, axis=0)

    # Split the array into 3 parts along axis 1 (columns)
    split_result_axis_1 = split_array(original_array, num_splits=3, axis=1)

    # Print the results
    print("Split along axis 0:")
    for i, arr in enumerate(split_result_axis_0):
        print(f"Sub-array {i}:\n{arr}")

    print("\nSplit along axis 1:")
    for i, arr in enumerate(split_result_axis_1):
        print(f"Sub-array {i}:\n{arr}")


Split along axis 0:
Sub-array 0:
[[1 2 3]]
Sub-array 1:
[[4 5 6]]
Sub-array 2:
[[7 8 9]]

Split along axis 1:
Sub-array 0:
[[1]
 [4]
 [7]]
Sub-array 1:
[[2]
 [5]
 [8]]
Sub-array 2:
[[3]
 [6]
 [9]]


In [96]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices. original_array = np.array([1, 2, 3, 4, 5])
                                                                                                      # indices_to_insert = [2, 4]
                                                                                                      # values_to_insert = [10, 11]
                                                                                                      # indices_to_delete = [1, 3]



def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert values into the original array
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)

    # Delete specified elements from the modified array
    # Note: Deletion should be done in reverse order to avoid index shifting issues
    for index in sorted(indices_to_delete)[::-1]:
        modified_array = np.delete(modified_array, index)

    return modified_array

# Example usage
if __name__ == "__main__":
    # Given original array
    original_array = np.array([1, 2, 3, 4, 5])

    # Indices to insert and their corresponding values
    indices_to_insert = [2, 4]
    values_to_insert = [10, 11]

    # Indices to delete
    indices_to_delete = [1, 3]

    # Perform insertion and deletion
    result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

    # Print the result
    print("Modified Array:", result_array)



Modified Array: [ 1 10  4 11  5]


In [97]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.



def create_and_add_arrays():
    # Create an array of random integers (e.g., shape (2, 5) for compatibility)
    arr1 = np.random.randint(0, 10, size=(2, 5))  # Random integers between 0 and 9

    # Create an array with integers from 1 to 10 (reshaped to match arr1)
    arr2 = np.arange(1, 11).reshape(2, 5)  # Reshape to (2, 5) for compatibility

    # Perform element-wise addition
    result = arr1 + arr2

    return arr1, arr2, result

# Example usage
if __name__ == "__main__":
    arr1, arr2, result = create_and_add_arrays()

    print("Array 1 (Random Integers):\n", arr1)
    print("\nArray 2 (Integers from 1 to 10):\n", arr2)
    print("\nResult of Element-wise Addition:\n", result)




Array 1 (Random Integers):
 [[9 7 1 5 0]
 [8 1 6 8 4]]

Array 2 (Integers from 1 to 10):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Result of Element-wise Addition:
 [[10  9  4  9  5]
 [14  8 14 17 14]]


In [98]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.


# Create an array with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)  # Start at 10, stop before 0, step -1

# Create an array with integers from 1 to 10
arr2 = np.arange(1, 11)  # Start at 1, stop before 11

# Perform element-wise subtraction
result = arr1 - arr2

# Print the results
print("Array 1 (Sequential Integers from 10 to 1):\n", arr1)
print("\nArray 2 (Integers from 1 to 10):\n", arr2)
print("\nResult of Element-wise Subtraction (arr1 - arr2):\n", result)



Array 1 (Sequential Integers from 10 to 1):
 [10  9  8  7  6  5  4  3  2  1]

Array 2 (Integers from 1 to 10):
 [ 1  2  3  4  5  6  7  8  9 10]

Result of Element-wise Subtraction (arr1 - arr2):
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [99]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.


# Create an array with random integers (for example, shape (3, 5))
arr1 = np.random.randint(0, 10, size=(3, 5))  # Random integers between 0 and 9

# Create an array with integers from 1 to 5
arr2 = np.arange(1, 6)  # This creates an array [1, 2, 3, 4, 5]

# To ensure arr2 can be multiplied with arr1, we need to reshape arr2
arr2_reshaped = arr2.reshape(1, -1)  # Reshape arr2 to (1, 5) for broadcasting

# Perform element-wise multiplication
result = arr1 * arr2_reshaped

# Print the results
print("Array 1 (Random Integers):\n", arr1)
print("\nArray 2 (Integers from 1 to 5):\n", arr2)
print("\nResult of Element-wise Multiplication:\n", result)



Array 1 (Random Integers):
 [[1 5 0 1 3]
 [7 4 1 2 7]
 [8 4 2 1 5]]

Array 2 (Integers from 1 to 5):
 [1 2 3 4 5]

Result of Element-wise Multiplication:
 [[ 1 10  0  4 15]
 [ 7  8  3  8 35]
 [ 8  8  6  4 25]]


In [100]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.


# Create an array with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)  # This generates [2, 4, 6, 8, 10]

# Create an array with integers from 1 to 5
arr2 = np.arange(1, 6)      # This generates [1, 2, 3, 4, 5]

# Perform element-wise division
result = arr1 / arr2

# Print the results
print("Array 1 (Even Integers from 2 to 10):\n", arr1)
print("\nArray 2 (Integers from 1 to 5):\n", arr2)
print("\nResult of Element-wise Division (arr1 / arr2):\n", result)



Array 1 (Even Integers from 2 to 10):
 [ 2  4  6  8 10]

Array 2 (Integers from 1 to 5):
 [1 2 3 4 5]

Result of Element-wise Division (arr1 / arr2):
 [2. 2. 2. 2. 2.]


In [7]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.


# Create an array with integers from 1 to 5
arr1 = np.arange(1, 6)  # This generates [1, 2, 3, 4, 5]

# Create another array with the same numbers reversed
arr2 = arr1[::-1]       # This generates [5, 4, 3, 2, 1]

# Perform element-wise exponentiation (arr1 raised to the power of arr2)
result = arr1 ** arr2   # Alternatively, you can use np.power(arr1, arr2)

# Print the results
print("Array 1 (Integers from 1 to 5):\n", arr1)
print("\nArray 2 (Reversed Array):\n", arr2)
print("\nResult of Element-wise Exponentiation (arr1 ** arr2):\n", result)



Array 1 (Integers from 1 to 5):
 [1 2 3 4 5]

Array 2 (Reversed Array):
 [5 4 3 2 1]

Result of Element-wise Exponentiation (arr1 ** arr2):
 [ 1 16 27 16  5]


In [9]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


def count_substring(arr, substring):
    return np.char.count(arr, substring)

# Example usage
if __name__ == "__main__":
    # Given array of strings
    arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

    # Substring to search for
    substring = 'hello'

    # Count occurrences
    counts = count_substring(arr, substring)

    # Print the result
    print("Array:", arr)
    print("Counts of substring '{}':\n".format(substring), counts)


Array: ['hello' 'world' 'hello' 'numpy' 'hello']
Counts of substring 'hello':
 [1 0 1 0 1]


In [11]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])



def extract_uppercase(arr):
    # Use a list comprehension to extract uppercase characters from each string
    uppercase_chars = [''.join([char for char in string if char.isupper()]) for string in arr]

    return uppercase_chars

# Example usage
if __name__ == "__main__":
    # Given array of strings
    arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

    # Extract uppercase characters
    result = extract_uppercase(arr)

    # Print the result
    print("Original Array:", arr)
    print("Uppercase characters extracted from each string:\n", result)




Original Array: ['Hello' 'World' 'OpenAI' 'GPT']
Uppercase characters extracted from each string:
 ['H', 'W', 'OAI', 'GPT']


In [14]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np
import re

def replace_whole_word(arr, old_substring, new_substring):
    # Use regex to replace only whole words
    pattern = r'\b' + re.escape(old_substring) + r'\b'

    # Replace using a list comprehension and re.sub
    updated_arr = np.array([re.sub(pattern, new_substring, string) for string in arr])

    return updated_arr

# Example usage
if __name__ == "__main__":
    # Given array of strings
    arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

    # Substring to replace and the new substring
    old_substring = 'apple'
    new_substring = 'orange'

    # Replace occurrences
    result = replace_whole_word(arr, old_substring, new_substring)

    # Print the result
    print("Original Array:\n", arr)
    print("\nUpdated Array after replacement:\n", result)




Original Array:
 ['apple' 'banana' 'grape' 'pineapple']

Updated Array after replacement:
 ['orange' 'banana' 'grape' 'pineapple']


In [17]:
# 59. Write a function that concatenates strings in a NumPy array element-wise. arr1 = np.array(['Hello', 'World']) arr2 = np.array(['Open', 'AI']).


def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

# Example usage
if __name__ == "__main__":
    # Given arrays of strings
    arr1 = np.array(['Hello', 'World'])
    arr2 = np.array(['Open', 'AI'])

    # Concatenate the strings element-wise
    result = concatenate_strings(arr1, arr2)

    # Print the result
    print("Array 1:", arr1)
    print("Array 2:", arr2)
    print("Concatenated Strings:\n", result)

Array 1: ['Hello' 'World']
Array 2: ['Open' 'AI']
Concatenated Strings:
 ['HelloOpen' 'WorldAI']


In [19]:
# 60. Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


def longest_string_length(arr):
    # Use numpy's vectorized operations to get lengths of each string
    lengths = np.char.str_len(arr)

    # Return the maximum length
    return np.max(lengths)

# Example usage
if __name__ == "__main__":
    # Given array of strings
    arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

    # Find the length of the longest string
    result = longest_string_length(arr)

    # Print the result
    print("Original Array:", arr)
    print("Length of the longest string:", result)



Original Array: ['apple' 'banana' 'grape' 'pineapple']
Length of the longest string: 9


In [20]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.


def generate_random_data(size=100, low=1, high=1000):
    # Generate random integers
    data = np.random.randint(low, high, size)

    # Compute statistics
    mean = np.mean(data)
    median = np.median(data)
    variance = np.var(data)
    std_deviation = np.std(data)

    # Return the results in a dictionary
    return {
        'mean': mean,
        'median': median,
        'variance': variance,
        'standard_deviation': std_deviation,
        'data': data  # Optional: include the generated data for reference
    }

# Example usage
if __name__ == "__main__":
    stats = generate_random_data()

    print("Generated Data:", stats['data'])
    print("\nMean:", stats['mean'])
    print("Median:", stats['median'])
    print("Variance:", stats['variance'])
    print("Standard Deviation:", stats['standard_deviation'])



Generated Data: [623  69 124 860  26 195 980 850 348  47 925 665 114 969 284 192 727 188
 940 877 916 616 350 299   7 265 815 163  47 825 970 298 152 878 995 474
 730 833 574 193 277 829 667 885 258 802 522 223 105 721 189  84 947  11
 337 792 237 733 312 833 226 483 951 813 189 515 214 341 495 440 983   9
 985 954 710 744 259 946  43 990  55 485 478  75 833  42 133 131 462 783
  50 404 126 436 362 392 652 701 995 170]

Mean: 492.22
Median: 468.0
Variance: 106959.37159999998
Standard Deviation: 327.04643645818857


In [21]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.


def generate_random_numbers_and_percentiles(size=50, low=1, high=100):
    # Generate random numbers
    data = np.random.randint(low, high, size)

    # Compute the 25th and 75th percentiles
    percentile_25 = np.percentile(data, 25)
    percentile_75 = np.percentile(data, 75)

    # Return the results in a dictionary
    return {
        'data': data,
        '25th_percentile': percentile_25,
        '75th_percentile': percentile_75
    }

# Example usage
if __name__ == "__main__":
    result = generate_random_numbers_and_percentiles()

    print("Generated Data:", result['data'])
    print("25th Percentile:", result['25th_percentile'])
    print("75th Percentile:", result['75th_percentile'])


Generated Data: [23 81 55 66 41 38 17 63  1 20 31 64 53 81 79 12 48 52  9  6 39 23 62 25
 53 66 60 87 98 91 12  7 65 73 82 29 24 26 14 80 43 87 95 74 79 74 56 96
 32 76]
25th Percentile: 25.25
75th Percentile: 75.5


In [22]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.


def compute_correlation(arr1, arr2):
    # Calculate the correlation coefficient matrix
    correlation_matrix = np.corrcoef(arr1, arr2)
    return correlation_matrix

# Example usage
if __name__ == "__main__":
    # Create two arrays representing two sets of variables
    arr1 = np.array([10, 20, 30, 40, 50])
    arr2 = np.array([5, 15, 25, 35, 45])

    # Compute the correlation coefficient
    result = compute_correlation(arr1, arr2)

    # Print the result
    print("Correlation Coefficient Matrix:\n", result)


Correlation Coefficient Matrix:
 [[1. 1.]
 [1. 1.]]


In [23]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


def multiply_matrices(mat1, mat2):
    return np.dot(mat1, mat2)

# Example usage
if __name__ == "__main__":
    # Define two matrices
    mat1 = np.array([[1, 2],
                     [3, 4]])

    mat2 = np.array([[5, 6],
                     [7, 8]])

    # Perform matrix multiplication
    result = multiply_matrices(mat1, mat2)

    # Print the result
    print("Matrix 1:\n", mat1)
    print("\nMatrix 2:\n", mat2)
    print("\nResult of Matrix Multiplication:\n", result)


Matrix 1:
 [[1 2]
 [3 4]]

Matrix 2:
 [[5 6]
 [7 8]]

Result of Matrix Multiplication:
 [[19 22]
 [43 50]]


In [24]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.


def calculate_percentiles_and_quartiles(size=50, low=10, high=1000):
    # Generate random integers
    data = np.random.randint(low, high, size)

    # Calculate percentiles
    percentile_10 = np.percentile(data, 10)
    median = np.percentile(data, 50)  # This is the median
    percentile_90 = np.percentile(data, 90)

    # Calculate quartiles
    first_quartile = np.percentile(data, 25)
    third_quartile = np.percentile(data, 75)

    # Return results in a dictionary
    return {
        'data': data,
        '10th_percentile': percentile_10,
        'median': median,
        '90th_percentile': percentile_90,
        'first_quartile': first_quartile,
        'third_quartile': third_quartile
    }

# Example usage
if __name__ == "__main__":
    result = calculate_percentiles_and_quartiles()

    print("Generated Data:", result['data'])
    print("10th Percentile:", result['10th_percentile'])
    print("Median (50th Percentile):", result['median'])
    print("90th Percentile:", result['90th_percentile'])
    print("First Quartile (25th Percentile):", result['first_quartile'])
    print("Third Quartile (75th Percentile):", result['third_quartile'])



Generated Data: [949 750 278 331 123 267 903 230 853 322 265 201 289 816 901  11 587 597
 554 744  51 207 845 495 789 779 800 643 342 843  49 694 362 777  20 798
 335 716 465 301 806 766 586 137 105 267 842 674 543 270]
10th Percentile: 121.2
Median (50th Percentile): 548.5
90th Percentile: 843.2
First Quartile (25th Percentile): 267.75
Third Quartile (75th Percentile): 778.5


In [25]:
# 66. Create a NumPy array of integers and find the index of a specific element.


def find_element_index(arr, value):
    indices = np.where(arr == value)[0]  # Get all indices where arr equals value
    if indices.size > 0:
        return indices[0]  # Return the first index
    else:
        return -1  # Return -1 if the value is not found

# Example usage
if __name__ == "__main__":
    # Create a NumPy array of integers
    arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

    # Value to find
    value_to_find = 50

    # Find the index of the specified element
    index = find_element_index(arr, value_to_find)

    # Print the result
    if index != -1:
        print(f"The index of {value_to_find} is: {index}")
    else:
        print(f"{value_to_find} is not found in the array.")


The index of 50 is: 4


In [26]:
# 67. Generate a random NumPy array and sort it in ascending order.


def generate_and_sort_random_array(size=50, low=10, high=1000):
    # Generate a random array of integers
    random_array = np.random.randint(low, high, size)

    # Sort the array in ascending order
    sorted_array = np.sort(random_array)

    return random_array, sorted_array

# Example usage
if __name__ == "__main__":
    original_array, sorted_array = generate_and_sort_random_array()

    print("Original Random Array:\n", original_array)
    print("\nSorted Array in Ascending Order:\n", sorted_array)


Original Random Array:
 [917 926 510  41 187 684 375 994 391 120 122 977 880 726 996 403  37 263
 409 314 647 529 617 955 738 661 618 306 430 308 872 594 655 139 519  30
 524 372  65 725  84  82 320 925 726 369 531 370 844 785]

Sorted Array in Ascending Order:
 [ 30  37  41  65  82  84 120 122 139 187 263 306 308 314 320 369 370 372
 375 391 403 409 430 510 519 524 529 531 594 617 618 647 655 661 684 725
 726 726 738 785 844 872 880 917 925 926 955 977 994 996]


In [28]:
# 68. Filter elements >20  in the given NumPy array. arr = np.array([12, 25, 6, 42, 8, 30])


# Create the NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_elements = arr[arr > 20]

# Print the result
print("Original Array:", arr)
print("Filtered Elements (greater than 20):", filtered_elements)


Original Array: [12 25  6 42  8 30]
Filtered Elements (greater than 20): [25 42 30]


In [29]:
# 69. Filter elements which are divisible by 3 from a given NumPy array. arr = np.array([1, 5, 8, 12, 15]).

# Create the NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements that are divisible by 3
filtered_elements = arr[arr % 3 == 0]

# Print the result
print("Original Array:", arr)
print("Filtered Elements (divisible by 3):", filtered_elements)


Original Array: [ 1  5  8 12 15]
Filtered Elements (divisible by 3): [12 15]


In [30]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. arr = np.array([10, 20, 30, 40, 50])

# Create the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements that are ≥ 20 and ≤ 40
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

# Print the result
print("Original Array:", arr)
print("Filtered Elements (≥ 20 and ≤ 40):", filtered_elements)


Original Array: [10 20 30 40 50]
Filtered Elements (≥ 20 and ≤ 40): [20 30 40]


In [31]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder. arr = np.array([1, 2, 3])


# Create the NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using the dtype attribute
byte_order = arr.dtype.byteorder

# Print the result
print("Array:", arr)
print("Byte Order:", byte_order)


Array: [1 2 3]
Byte Order: =


In [32]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`. arr = np.array([1, 2, 3], dtype=np.int32)


# Create the NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array
print("Original Array:", arr)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the modified array after byte swapping
print("Array after Byte Swapping:", arr)


Original Array: [1 2 3]
Array after Byte Swapping: [16777216 33554432 50331648]


In [33]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)


# Create the NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the new array and its byte order
print("Swapped Byte Order Array:", swapped_arr)
print("Swapped Byte Order Array's Byte Order:", swapped_arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
Swapped Byte Order Array: [16777216 33554432 50331648]
Swapped Byte Order Array's Byte Order: >


In [34]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)

import sys

# Create the NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Determine the system's endianness
if sys.byteorder == 'little':
    # If system is little-endian, swap to big-endian
    swapped_arr = arr.newbyteorder('>')
else:
    # If system is big-endian, swap to little-endian
    swapped_arr = arr.newbyteorder('<')

# Print the swapped array and its byte order
print("Swapped Byte Order Array:", swapped_arr)
print("Swapped Byte Order Array's Byte Order:", swapped_arr.dtype.byteorder)



Original Array: [1 2 3]
Original Byte Order: =
Swapped Byte Order Array: [16777216 33554432 50331648]
Swapped Byte Order Array's Byte Order: >


In [35]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
import sys

# Create the NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Determine the system's endianness
system_endianness = sys.byteorder
print("System Endianness:", system_endianness)

# Check if byte swapping is necessary
if (arr.dtype.byteorder == '=' and system_endianness == 'little') or \
   (arr.dtype.byteorder == '>' and system_endianness == 'little') or \
   (arr.dtype.byteorder == '<' and system_endianness == 'big'):
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")



Original Array: [1 2 3]
Original Byte Order: =
System Endianness: little
Byte swapping is necessary.


In [37]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.


# Create the original NumPy array with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Print both arrays to check if arr1 is affected
print("Original Array (arr1):", arr1)
print("Modified Copy Array (copy_arr):", copy_arr)


Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy Array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [38]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.


# Create a 2D NumPy array (3x3) with random integers between 0 and 10
matrix = np.random.randint(0, 10, size=(3, 3))

# Print the original matrix
print("Original Matrix:\n", matrix)

# Extract a slice from the matrix (for example, the first two rows and columns)
view_slice = matrix[:2, :2]

# Print the extracted slice
print("\nView Slice before modification:\n", view_slice)

# Modify an element in the view_slice
view_slice[0, 0] = 99

# Print both the modified slice and the original matrix to observe changes
print("\nModified View Slice:\n", view_slice)
print("\nOriginal Matrix after modifying View Slice:\n", matrix)






Original Matrix:
 [[5 7 3]
 [3 1 4]
 [5 8 9]]

View Slice before modification:
 [[5 7]
 [3 1]]

Modified View Slice:
 [[99  7]
 [ 3  1]]

Original Matrix after modifying View Slice:
 [[99  7  3]
 [ 3  1  4]
 [ 5  8  9]]


In [39]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


# Create a NumPy array with values from 1 to 12 and reshape it to (4, 3)
array_a = np.arange(1, 13).reshape(4, 3)

# Print the original array
print("Original Array (array_a):\n", array_a)

# Extract a slice from array_a
view_b = array_a[1:3, 1:3]  # Extracting a 2x2 slice from the second and third rows and columns

# Print the extracted slice
print("\nExtracted Slice (view_b) before modification:\n", view_b)

# Broadcast the addition of 5 to view_b
view_b += 5

# Print both arrays to check if array_a is affected
print("\nModified Slice (view_b):\n", view_b)
print("\nOriginal Array (array_a) after modifying view_b:\n", array_a)



Original Array (array_a):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracted Slice (view_b) before modification:
 [[5 6]
 [8 9]]

Modified Slice (view_b):
 [[10 11]
 [13 14]]

Original Array (array_a) after modifying view_b:
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


In [40]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.


# Create a NumPy array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Print the original array
print("Original Array (orig_array):\n", orig_array)

# Create a reshaped view of orig_array with shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)

# Print the reshaped view
print("\nReshaped View (reshaped_view):\n", reshaped_view)

# Modify an element in the reshaped view
reshaped_view[0, 0] = 99

# Print both arrays to check if orig_array is affected
print("\nModified Reshaped View (reshaped_view):\n", reshaped_view)
print("\nOriginal Array (orig_array) after modifying reshaped_view:\n", orig_array)




Original Array (orig_array):
 [[1 2 3 4]
 [5 6 7 8]]

Reshaped View (reshaped_view):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified Reshaped View (reshaped_view):
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]

Original Array (orig_array) after modifying reshaped_view:
 [[99  2  3  4]
 [ 5  6  7  8]]


In [41]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


# Create a NumPy array of shape (3, 4) with random integers between 0 and 10
data = np.random.randint(0, 10, size=(3, 4))

# Print the original array
print("Original Array (data):\n", data)

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()  # Using .copy() to ensure it's a separate copy

# Print the copied array
print("\nCopied Array (data_copy) with elements > 5:\n", data_copy)

# Modify an element in data_copy
if data_copy.size > 0:  # Check if there are elements to modify
    data_copy[0] = 99

# Print both arrays to check if data is affected
print("\nModified Copied Array (data_copy):\n", data_copy)
print("\nOriginal Array (data) after modifying data_copy:\n", data)



Original Array (data):
 [[4 9 1 7]
 [1 7 5 0]
 [8 4 6 1]]

Copied Array (data_copy) with elements > 5:
 [9 7 7 8 6]

Modified Copied Array (data_copy):
 [99  7  7  8  6]

Original Array (data) after modifying data_copy:
 [[4 9 1 7]
 [1 7 5 0]
 [8 4 6 1]]


In [42]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them..


# Create two matrices A and B of shape (3, 3) with random integers
A = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 9
B = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 9

# Print the original matrices
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# Perform addition
C_add = A + B

# Perform subtraction
C_sub = A - B

# Print the results of addition and subtraction
print("\nResult of Addition (A + B):\n", C_add)
print("\nResult of Subtraction (A - B):\n", C_sub)



Matrix A:
 [[8 7 8]
 [7 4 6]
 [8 3 4]]

Matrix B:
 [[6 2 8]
 [9 7 5]
 [4 5 5]]

Result of Addition (A + B):
 [[14  9 16]
 [16 11 11]
 [12  8  9]]

Result of Subtraction (A - B):
 [[ 2  5  0]
 [-2 -3  1]
 [ 4 -2 -1]]


In [43]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.


# Generate matrix C of shape (3, 2) with random integers
C = np.random.randint(1, 10, size=(3, 2))  # Random integers between 1 and 9

# Generate matrix D of shape (2, 4) with random integers
D = np.random.randint(1, 10, size=(2, 4))  # Random integers between 1 and 9

# Print the generated matrices
print("Matrix C (3x2):\n", C)
print("\nMatrix D (2x4):\n", D)

# Perform matrix multiplication
result = np.dot(C, D)  # Alternatively, you can use result = C @ D

# Print the result of matrix multiplication
print("\nResult of Matrix Multiplication (C @ D):\n", result)


Matrix C (3x2):
 [[2 5]
 [5 2]
 [7 3]]

Matrix D (2x4):
 [[3 9 3 9]
 [4 9 5 3]]

Result of Matrix Multiplication (C @ D):
 [[26 63 31 33]
 [23 63 25 51]
 [33 90 36 72]]


In [44]:
# 83. Create a matrix `E` and find its transpose.


# Create a matrix E of shape (3, 4) with random integers
E = np.random.randint(1, 10, size=(3, 4))  # Random integers between 1 and 9

# Print the original matrix
print("Original Matrix E:\n", E)

# Find the transpose of the matrix
E_transpose = E.T

# Print the transposed matrix
print("\nTransposed Matrix E:\n", E_transpose)


Original Matrix E:
 [[8 1 9 9]
 [3 7 1 5]
 [9 9 2 3]]

Transposed Matrix E:
 [[8 3 9]
 [1 7 9]
 [9 1 2]
 [9 5 3]]


In [45]:
# 84. Generate a square matrix `F` and compute its determinant.


# Generate a square matrix F of shape (3, 3) with random integers
F = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 9

# Print the original matrix
print("Square Matrix F:\n", F)

# Compute the determinant of the matrix
determinant_F = np.linalg.det(F)

# Print the determinant
print("\nDeterminant of Matrix F:", determinant_F)


Square Matrix F:
 [[4 2 7]
 [1 5 3]
 [5 9 7]]

Determinant of Matrix F: -63.99999999999998


In [46]:
# 85. Create a square matrix `G` and find its inverse.


# Generate a square matrix G of shape (3, 3) with random integers
G = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 9

# Print the original matrix
print("Square Matrix G:\n", G)

# Compute the determinant to check if the matrix is invertible
determinant_G = np.linalg.det(G)
print("\nDeterminant of Matrix G:", determinant_G)

# Check if the determinant is non-zero before calculating the inverse
if determinant_G != 0:
    # Compute the inverse of the matrix
    G_inverse = np.linalg.inv(G)
    print("\nInverse of Matrix G:\n", G_inverse)
else:
    print("\nMatrix G is not invertible (determinant is zero).")


Square Matrix G:
 [[5 4 1]
 [5 1 1]
 [9 3 3]]

Determinant of Matrix G: -18.000000000000004

Inverse of Matrix G:
 [[ 0.          0.5        -0.16666667]
 [ 0.33333333 -0.33333333  0.        ]
 [-0.33333333 -1.16666667  0.83333333]]
